language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
install:
  - "cpanm --notest DBIx::Class | tail -n 1"
  - "cpanm --notest Template | tail -n 1"
  - "cpanm --notest Config::Tiny | tail -n 1"
  - "cpanm --notest DBI | tail -n 1"
  - "cpanm --notest DBD::mysql | tail -n 1"
  - "cpanm --notest Moose | tail -n 1"
  - "cpanm --notest XML::Twig | tail -n 1"
  - "cpanm --notest HTML::Parser | tail -n 1"
  - "cpanm --notest JSON | tail -n 1"
  - "cpanm --notest Bio::Phylo | tail -n 1"
  - "git clone https://github.com/bioperl/bioperl-live.git; export PERL5LIB=$( pwd )/bioperl-live:$PERL5LIB"
  - "git clone https://github.com/bioperl/bioperl-run.git; export PERL5LIB=$( pwd )/bioperl-run/lib:$PERL5LIB"
